//! Autogenerated weights for ethereum_beacon_client
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-10-25, STEPS: `10`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("/tmp/snowbridge/spec.json"), DB CACHE: 1024

// Executed Command:
// ./target/release/snowbridge
// benchmark
// pallet
// --chain
// /tmp/snowbridge/spec.json
// --execution=wasm
// --pallet
// ethereum_beacon_client
// --extrinsic
// *
// --steps
// 10
// --repeat
// 10
// --output
// runtime/snowbase/src/weights/ethereum_beacon_client.rs
// --template
// templates/runtime-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use frame_support::weights::constants::RocksDbWeight;
use sp_std::marker::PhantomData;

/// Weight functions for ethereum_beacon_client.
pub struct SnowbridgeWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> ethereum_beacon_client::WeightInfo for SnowbridgeWeight<T> {
	// Storage: EthereumBeaconClient Blocked (r:1 w:0)
	// Storage: EthereumBeaconClient LatestFinalizedHeaderState (r:1 w:0)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: EthereumBeaconClient ValidatorsRoot (r:1 w:0)
	// Storage: EthereumBeaconClient SyncCommittees (r:2 w:1)
	// Storage: EthereumBeaconClient CounterForSyncCommittees (r:1 w:0)
	fn sync_committee_period_update() -> Weight {
		Weight::from_ref_time(129_357_000_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(7 as u64))
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
	// Storage: EthereumBeaconClient Blocked (r:1 w:0)
	// Storage: EthereumBeaconClient LatestFinalizedHeaderState (r:1 w:0)
	// Storage: EthereumBeaconClient SyncCommittees (r:1 w:0)
	// Storage: EthereumBeaconClient ValidatorsRoot (r:1 w:0)
	// Storage: EthereumBeaconClient ExecutionHeaders (r:1 w:1)
	// Storage: EthereumBeaconClient CounterForExecutionHeaders (r:1 w:1)
	// Storage: EthereumBeaconClient LatestExecutionHeaderState (r:1 w:1)
	// Storage: EthereumBeaconClient ExecutionHeadersMapping (r:0 w:1)
	fn import_execution_header() -> Weight {
		Weight::from_ref_time(137_048_000_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(7 as u64))
			.saturating_add(RocksDbWeight::get().writes(4 as u64))
	}
}